/**
 * Basic Verilator Compilation Example
 * 
 * This example demonstrates the fundamental Verilator compilation process
 * and common compilation options. It serves as a minimal working example.
 * 
 * Verilator Compilation Process:
 *   1. Verilator parses Verilog/SystemVerilog source files
 *   2. Generates C++ wrapper classes in obj_dir/ directory
 *   3. Compiles C++ testbench with generated wrappers
 *   4. Links everything into an executable
 * 
 * Key Compilation Flags:
 *   --cc          : Generate C++ code (required for C++ testbenches)
 *   --exe         : Generate executable (combines compilation and linking)
 *   --build       : Automatically build after generation (convenience flag)
 *   -O0, -O1, -O2, -O3 : Optimization levels (higher = faster simulation, slower compile)
 *   --trace       : Enable VCD waveform tracing
 *   --trace-fst   : Enable FST waveform tracing (smaller files)
 *   --coverage    : Enable code coverage collection
 *   --lint-only   : Only check syntax, don't generate code
 *   -I<dir>       : Add include directory for `include directives
 *   -D<macro>     : Define preprocessor macro
 * 
 * Compilation Output:
 *   - obj_dir/V<module_name>.cpp : Generated C++ wrapper implementation
 *   - obj_dir/V<module_name>.h   : Generated C++ wrapper header
 *   - obj_dir/V<module_name>     : Executable (if --exe --build used)
 * 
 * Usage examples:
 *   # Basic compilation (minimal flags)
 *   verilator --cc --exe --build basic_compilation.v basic_compilation.cpp
 *   
 *   # With optimization (recommended for production)
 *   verilator -O2 --cc --exe --build basic_compilation.v basic_compilation.cpp
 *   
 *   # With tracing (for waveform generation)
 *   verilator --trace --cc --exe --build basic_compilation.v basic_compilation.cpp
 *   
 *   # With coverage (for code coverage analysis)
 *   verilator --coverage --cc --exe --build basic_compilation.v basic_compilation.cpp
 *   
 *   # Lint only (syntax checking without compilation)
 *   verilator --lint-only basic_compilation.v
 */

#include <iostream>      // Console I/O
#include <verilated.h>     // Verilator core library
#include "Vbasic_compilation.h"  // Generated wrapper class

int main(int argc, char** argv) {
    // ========================================================================
    // STEP 1: Initialize Verilator
    // ========================================================================
    // Verilated::commandArgs() must be called before creating any Verilator
    // objects. It processes command-line arguments that Verilator understands.
    Verilated::commandArgs(argc, argv);
    
    std::cout << "========================================" << std::endl;
    std::cout << "Basic Verilator Compilation Example" << std::endl;
    std::cout << "========================================" << std::endl;
    
    // ========================================================================
    // STEP 2: Create DUT Instance
    // ========================================================================
    // The generated class name follows the pattern: V<module_name>
    // For module "basic_compilation", the class is "Vbasic_compilation".
    // This class is generated by Verilator during compilation.
    Vbasic_compilation* dut = new Vbasic_compilation;
    
    // ========================================================================
    // STEP 3: Evaluate Design
    // ========================================================================
    // eval() evaluates all combinational logic in the design.
    // For this simple example (empty module), it doesn't do much, but
    // it demonstrates the basic pattern: create DUT, call eval().
    dut->eval();
    
    std::cout << "DUT instantiated and evaluated successfully." << std::endl;
    std::cout << "This confirms Verilator compilation worked correctly." << std::endl;
    std::cout << "========================================" << std::endl;
    
    // ========================================================================
    // STEP 4: Cleanup
    // ========================================================================
    // Always call final() before deleting the DUT object.
    // This ensures proper cleanup of Verilator internals.
    dut->final();
    delete dut;
    
    return 0;
}
