/**
 * File I/O C++ Testbench for Verilator
 * 
 * This testbench demonstrates file-based test vector management:
 * - Reading test vectors from external files
 * - Writing test results to output files
 * - Structured test data management
 * - Separation of test data from test code
 * 
 * Benefits of File-Based Test Vectors:
 *   - Test data can be modified without recompiling
 *   - Test vectors can be generated by scripts or tools
 *   - Results can be logged for regression testing
 *   - Easier to manage large test suites
 *   - Test data can be shared across different testbenches
 * 
 * File Format (test_vectors.txt):
 *   - One test vector per line
 *   - Format: <input_a> <input_b> <expected_output>
 *   - Lines starting with # or / are treated as comments
 *   - Empty lines are ignored
 *   - Example:
 *       0 0 0
 *       0 1 0
 *       1 0 0
 *       1 1 1
 * 
 * Usage:
 *   verilator --cc --exe --build -I../../dut/simple_gates ../../dut/simple_gates/and_gate.v file_io_test.cpp
 *   ./obj_dir/Vand_gate
 * 
 * Output:
 *   - Console: Test progress and summary
 *   - test_results.txt: Detailed test results in tabular format
 */

#include <iostream>      // Console I/O
#include <fstream>       // File I/O (ifstream, ofstream)
#include <sstream>        // String stream for parsing
#include <vector>         // Dynamic array for test vectors
#include <cassert>        // Assertions
#include <verilated.h>    // Verilator core
#include "Vand_gate.h"    // Generated wrapper

/**
 * TestVector Structure
 * 
 * Represents a single test case with inputs and expected output.
 * This structure makes test data self-documenting and easy to manage.
 */
struct TestVector {
    uint8_t a;         // Input A
    uint8_t b;         // Input B
    uint8_t expected;  // Expected output
};

/**
 * Read Test Vectors from File
 * 
 * Parses a text file containing test vectors and returns them as a vector.
 * 
 * File Format:
 *   - One test vector per line: <a> <b> <expected>
 *   - Comments: Lines starting with '#' or '/'
 *   - Empty lines are skipped
 * 
 * @param filename Path to test vector file
 * @return Vector of test vectors, empty if file cannot be opened
 */
std::vector<TestVector> read_test_vectors(const std::string& filename) {
    std::vector<TestVector> vectors;
    std::ifstream file(filename);
    
    // Check if file opened successfully
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open file " << filename << std::endl;
        return vectors;  // Return empty vector on error
    }
    
    // Read file line by line
    std::string line;
    while (std::getline(file, line)) {
        // Skip comments and empty lines
        // Comments can start with '#' (common in test files) or '/' (C-style)
        if (line.empty() || line[0] == '/' || line[0] == '#') {
            continue;
        }
        
        // Parse line: extract three space-separated values
        TestVector tv;
        std::istringstream iss(line);  // Create string stream from line
        iss >> tv.a >> tv.b >> tv.expected;  // Extract values
        
        // Add to vector if parsing succeeded
        vectors.push_back(tv);
    }
    
    file.close();
    return vectors;
}

int main(int argc, char** argv) {
    // ========================================================================
    // STEP 1: Initialize Verilator
    // ========================================================================
    Verilated::commandArgs(argc, argv);
    
    std::cout << "========================================" << std::endl;
    std::cout << "File I/O C++ Testbench Example" << std::endl;
    std::cout << "========================================" << std::endl;
    
    // ========================================================================
    // STEP 2: Load Test Vectors from File
    // ========================================================================
    std::vector<TestVector> test_vectors = read_test_vectors("test_vectors.txt");
    
    // Fallback: If file doesn't exist or is empty, use default test vectors
    // This makes the testbench more robust and easier to use.
    if (test_vectors.empty()) {
        std::cerr << "Warning: No test vectors found in file. Using default test vectors." << std::endl;
        // Create default test vectors (all combinations for 2-input AND gate)
        test_vectors = {
            {0, 0, 0},  // 0 AND 0 = 0
            {0, 1, 0},  // 0 AND 1 = 0
            {1, 0, 0},  // 1 AND 0 = 0
            {1, 1, 1}   // 1 AND 1 = 1
        };
    }
    
    std::cout << "Loaded " << test_vectors.size() << " test vectors" << std::endl;
    
    // ========================================================================
    // STEP 3: Create DUT Instance
    // ========================================================================
    Vand_gate* dut = new Vand_gate;
    
    // ========================================================================
    // STEP 4: Open Output File for Results
    // ========================================================================
    // Write test results to a file for later analysis, regression testing, etc.
    std::ofstream result_file("test_results.txt");
    if (!result_file.is_open()) {
        std::cerr << "Error: Cannot open output file test_results.txt" << std::endl;
        return 1;  // Exit with error code
    }
    
    // Write header to results file
    result_file << "Test Results\n";
    result_file << "=============\n";
    result_file << "Test |  a  |  b  |  y  | Expected | Pass/Fail\n";
    result_file << "-----|-----|-----|-----|----------|----------\n";
    
    // ========================================================================
    // STEP 5: Run Test Suite
    // ========================================================================
    int pass_count = 0;
    int fail_count = 0;
    
    // Apply each test vector to the DUT
    for (size_t i = 0; i < test_vectors.size(); i++) {
        const auto& tv = test_vectors[i];
        
        // Apply inputs to DUT
        dut->a = tv.a;
        dut->b = tv.b;
        
        // Evaluate combinational logic
        dut->eval();
        
        // Check if output matches expected value
        bool passed = (dut->y == tv.expected);
        if (passed) {
            pass_count++;
        } else {
            fail_count++;
        }
        
        // Print to console (for real-time monitoring)
        std::cout << "Test " << (i + 1) << ": a=" << (int)tv.a << ", b=" << (int)tv.b 
                  << ", y=" << (int)dut->y << ", expected=" << (int)tv.expected 
                  << " [" << (passed ? "PASS" : "FAIL") << "]" << std::endl;
        
        // Write to file (for permanent record)
        result_file << "  " << (i + 1) << "  |  " << (int)tv.a << "  |  " << (int)tv.b 
                    << "  |  " << (int)dut->y << "  |    " << (int)tv.expected 
                    << "     |   " << (passed ? "PASS" : "FAIL") << "\n";
    }
    
    // Write summary to file
    result_file << "\nSummary: " << pass_count << " passed, " << fail_count << " failed\n";
    result_file.close();  // Close file (important for flushing buffers)
    
    // ========================================================================
    // STEP 6: Print Summary and Cleanup
    // ========================================================================
    std::cout << "\n========================================" << std::endl;
    std::cout << "Test Summary: " << pass_count << " passed, " << fail_count << " failed" << std::endl;
    std::cout << "Results written to test_results.txt" << std::endl;
    std::cout << "========================================" << std::endl;
    
    // Cleanup
    dut->final();
    delete dut;
    
    // Return exit code: 0 = success, non-zero = failure
    // This is important for automated test scripts and CI/CD pipelines.
    return (fail_count == 0) ? 0 : 1;
}
