/**
 * File I/O Testbench Example
 * 
 * This testbench demonstrates file-based verification patterns:
 * - Reading test vectors from files ($readmemh, $readmemb)
 * - Writing results to files ($fopen, $fwrite, $fclose)
 * - File-based testbench patterns (scalable for large test suites)
 * - Automated test vector application
 * - Result logging to files
 * 
 * Verification Methodology Context:
 * - File-based test vectors are common in verification
 * - Allows separation of test data from testbench code
 * - Enables easy test vector generation and modification
 * - In UVM, this pattern evolves into transaction-based verification where
 *   sequences generate transactions (similar to reading test vectors)
 * - See: https://github.com/universal-verification-methodology/core for
 *   advanced transaction-based patterns
 * 
 * File I/O System Tasks:
 * - $readmemh: Read hexadecimal values from file into memory array
 * - $readmemb: Read binary values from file into memory array
 * - $fopen: Open file for writing (returns file handle)
 * - $fwrite/$fdisplay: Write formatted text to file
 * - $fclose: Close file handle
 * 
 * Usage:
 *   iverilog -o file_read_test file_read_test.v ../../dut/simple_gates/and_gate.v
 *   vvp file_read_test
 *   cat test_results.txt  # View results
 * 
 * Note: Create test_vectors.hex and expected_results.hex before running
 */

`timescale 1ns/1ps

module file_read_test;

    // ========================================================================
    // Testbench Signal Declarations
    // ========================================================================
    
    reg  a, b;      // Input signals (drive DUT)
    wire y;         // Output signal (observe DUT)
    
    // File I/O variables
    integer file_handle;  // File handle for output file (returned by $fopen)
    integer i;            // Loop counter
    
    // Memory arrays for storing test vectors and expected results
    // Format: [0:3] means array indices 0, 1, 2, 3 (4 elements)
    // [1:0] means each element is 2 bits wide
    reg [1:0] test_vector [0:3];  // Memory array: stores test vectors from file
    reg [1:0] expected [0:3];    // Memory array: stores expected results from file

    // ========================================================================
    // DUT (Design Under Test) Instantiation
    // ========================================================================
    
    and_gate dut (
        .a(a),  // Connect testbench signal to DUT input
        .b(b),  // Connect testbench signal to DUT input
        .y(y)   // Observe DUT output
    );

    // ========================================================================
    // Main Test Sequence
    // ========================================================================
    // This testbench demonstrates a file-based verification flow:
    // 1. Read test vectors from file (separates data from code)
    // 2. Read expected results from file
    // 3. Apply each test vector to DUT
    // 4. Compare actual vs. expected results
    // 5. Write results to file (for later analysis)
    // 
    // Benefits of File-Based Testing:
    // - Test vectors can be generated by external tools
    // - Easy to add/modify test cases without changing code
    // - Results can be analyzed offline
    // - Scalable to thousands of test vectors
    
    initial begin
        $display("========================================");
        $display("File I/O Testbench Example");
        $display("========================================");
        
        // ====================================================================
        // Step 1: Read Test Vectors from Files
        // ====================================================================
        // $readmemh reads hexadecimal values from a file into a memory array
        // File format: One value per line (hexadecimal)
        // Example test_vectors.hex:
        //   00
        //   01
        //   10
        //   11
        // 
        // test_vector[0] = 2'h00 (a=0, b=0)
        // test_vector[1] = 2'h01 (a=0, b=1)
        // test_vector[2] = 2'h10 (a=1, b=0)
        // test_vector[3] = 2'h11 (a=1, b=1)
        
        $readmemh("test_vectors.hex", test_vector);      // Read test inputs
        $readmemh("expected_results.hex", expected);     // Read expected outputs
        
        $display("Read test vectors from file");
        $display("Test vectors:");
        for (i = 0; i < 4; i = i + 1) begin
            // Display each test vector
            // test_vector[i][1] = bit 1 (a input)
            // test_vector[i][0] = bit 0 (b input)
            $display("  Vector %0d: a=%b, b=%b, expected=%b", 
                     i, test_vector[i][1], test_vector[i][0], expected[i][0]);
        end
        
        // ====================================================================
        // Step 2: Open Output File for Results
        // ====================================================================
        // $fopen opens a file for writing
        // Mode "w" = write (overwrites existing file)
        // Returns: File handle (integer) or 0 if failed
        // Always check if file opened successfully!
        
        file_handle = $fopen("test_results.txt", "w");
        if (file_handle == 0) begin
            $error("Failed to open output file 'test_results.txt'");
            $finish;  // Exit if file open failed
        end
        
        // Write header to file
        $fwrite(file_handle, "Test Results\n");
        $fwrite(file_handle, "=============\n");
        $fwrite(file_handle, "Time |  a  |  b  |  y  | Expected | Pass/Fail\n");
        $fwrite(file_handle, "-----|-----|-----|-----|----------|----------\n");
        
        // ====================================================================
        // Step 3: Apply Test Vectors and Check Results
        // ====================================================================
        // Loop through all test vectors, apply them to DUT, and check results
        
        for (i = 0; i < 4; i = i + 1) begin
            // Extract inputs from test vector
            // test_vector[i] is 2 bits: [1:0]
            // test_vector[i][1] = a input (bit 1)
            // test_vector[i][0] = b input (bit 0)
            a = test_vector[i][1];
            b = test_vector[i][0];
            #5;  // Wait for combinational logic to propagate
            
            // Display current test on console
            $display("Time %0t: a=%b, b=%b, y=%b, expected=%b", 
                     $time, a, b, y, expected[i][0]);
            
            // Self-checking: Compare actual vs. expected
            // === is case equality (includes X and Z states)
            if (y === expected[i][0]) begin
                // Test passed - write to file
                $fwrite(file_handle, "%4t |  %b  |  %b  |  %b  |    %b     |   PASS\n",
                        $time, a, b, y, expected[i][0]);
            end else begin
                // Test failed - write to file and report error
                $fwrite(file_handle, "%4t |  %b  |  %b  |  %b  |    %b     |   FAIL\n",
                        $time, a, b, y, expected[i][0]);
                $error("Test failed at vector %0d: expected %b, got %b", 
                       i, expected[i][0], y);
            end
        end
        
        // ====================================================================
        // Step 4: Close Output File
        // ====================================================================
        // Always close files when done to ensure all data is written
        // and file handles are released
        
        $fclose(file_handle);
        
        $display("\nResults written to test_results.txt");
        $display("View results with: cat test_results.txt");
        $display("========================================");
        #10;
        $finish;  // Terminate simulation
    end

endmodule
